languageCode = "en-us"
title = "Zach Rusell: Web Developer & SEO from Philadelphia"
baseURL = "https://zachrussell.net"
theme = "zachrussell"
canonifyURLs = true
enableRobotsTXT = true
[params]
  description= "Zachary Russell is an Entrepreneur, Software Engineer & SEO from Philadelphia. Learn more about Zach today"
  [params.publisher]
    name = "Zachary Russell"
  [params.publisher.logo]
    url = "/images/zachary-russell.jpeg"
    width = 60 
    height = 60
    

[permalinks]
    post = "/blog/:title/"


[menu]
  [[menu.main]]
    identifier = "About Me"
    title = "About Me"
    name = "About Me"
    url = "/about-me/"
    weight = "1"

  [[menu.main]]
    identifier = "WordPress Development"
    title = "WordPress Development Services"
    name = "WordPress Development"
    url = "/wordpress-development"
    weight = "2"

  [[menu.main]]
    identifier = "Blog"
    title = "Blog"
    name = "Blog"
    url = "/blog/"
    weight = "3"

  [[menu.main]]
    identifier = "Contact"
    title = "Contact Me"
    name = "Contact"
    url = "/contact"
    weight = "999"
[author]
name = "Zachary Russell"

